### ISSUE TITLE
程序不能根据用户输入的字符，结束生成四则运算题目

### ISSUE THREAD

**Issue by Orangeyc123** [Lexyguo/mask#1]
在我的测试当中，程序生成随机数量的题目，直到题量达到随机产生数字后结束程序运行。
你的代码我没有研究，如果有此类功能可以忽略此问题，基于有此情况下，我建议：请在开头或显眼的位置提示用户，以便良好的人机交互。

**Comment by Lexyguo** [comment]
原先的代码并没有结束生成四则运算题目的功能，修改后已经增减此功能，且在开始时提示用户

**Comment by Lexyguo** [comment]
原先的代码并没有结束生成四则运算题目的功能，修改后已经增减此功能，且在开始时提示用户
