### ISSUE TITLE
当程序拒绝用户输入的错误数据后，不能让用户重新输入一遍

### ISSUE THREAD

**Issue by Orangeyc123** [Lexyguo/mask#2]
1、如果用户输入 N / 0，程序不会拒绝输入
2、如果用户输入除数字及 / 之外的其他字符（含空格、小数点等），程序不会拒绝输入

我理解下的错误数据意思是无效的数据，即以上两个问题
那你的问题就是：随机产生题目，输入答案时，只要是不匹配正确答案的，都是错的，并不能拒绝输入，或再输入一遍（这个问题要改）

如果错误数据的意思是包含错误的答案，我觉得这个其实是不必要的，老师给的任务2要求是有正确率的存在，如果答案错误要求再输入一遍，就没有计算正确率的必要了。
换个思路，也可以是第一次输入答案错误就计入错误题数，直到输入正确答案为止。（这个无所谓）

看你自己的想法

**Comment by Lexyguo** [comment]
我理解的错误数据应该是格式不正确的格式，予以错误格式输入的提示且可以重新输入答案，但不算入错误题数中，只有错误答案直接算入错误题数中

**Comment by Lexyguo** [comment]
经过修改的代码已经修正不能拒绝输入的部分，且不算入错误题数中
